---
image: php:7.3

test:php7.3:
  image: php:7.3
  stage: test
  cache:
    paths:
      - vendor/
  services:
    - memcached
    - redis
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq curl git libcurl4-gnutls-dev libmemcached11 libmemcached-dev libxml2-dev libbz2-dev
      libzip-dev wget zlib1g-dev zip automake autoconf libtool g++
    # Install PHP extensions
    - docker-php-ext-install curl json mbstring xml zip
    # Install PECL extensions
    - pecl install igbinary redis xdebug-beta
    - docker-php-ext-enable igbinary redis xdebug
    - pecl download memcached-3.1.3
    - tar xzvf memcached-3.1.3.tgz
    - cd memcached-3.1.3
    - phpize
    - ./configure --enable-memcached-igbinary --enable-memcached-json
    - make
    - make install
    - cd ..
    - rm -rf memcached-3.1.3*
    - docker-php-ext-enable memcached
    # Install and run Composer
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/bin/composer
    - composer install
  script:
    # composer.json normalization
    - composer normalize --dry-run --indent-size=1 --indent-style=tab
    # Check if syntax errors was fixed with php-cs-fixer
    - vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
    # Analyse code with PHPStan
    # - vendor/bin/phpstan analyse
    # PHPMD
    # - vendor/bin/phpmd src/ text phpmd.xml
    # - vendor/bin/phpmd tests/ text phpmd.xml
    # Run PHPUnit
    - vendor/bin/phpunit --colors=never
    # ApiGen
    - vendor/bin/apigen generate src --destination build/api/
  artifacts:
    paths:
      - build/coverage/
      - build/api/
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

pages:
  stage: deploy
  dependencies:
    - test:php7.3
  environment:
    name: production
    url: https://the-framework.gitlab.io
  script:
    - mkdir public/
    - mv build/coverage/ public/
    - mv build/api/ public/
    - curl -sS https://the-framework.gitlab.io/redirect.php | php
  artifacts:
    paths:
      - public
  only:
    - master
