version: "3"
services:
  package:
    image: registry.gitlab.com/aplus-framework/images/package
    container_name: package-cache
    working_dir: /package
    volumes:
      - .:/package
    depends_on:
      - memcached
      - redis
    tty: true
  memcached:
    image: memcached:alpine
    container_name: cache-memcached
  redis:
    image: redis:alpine
    container_name: cache-redis
